### ISSUE TITLE
一直提示SECRET_KEY为空

### ISSUE THREAD

**Issue by acldm** [zmrenwu/pythonzh.cn#10]
使用python manage.py migrate时一直报错SECRET_KEY不能为空

**Comment by ghost** [comment]
为了安全，我把SECRET_KEY删了，你可以自己随便加一个随机字符串上去。另外这个项目存在问题，可能运行不起来。

**Comment by jcops** [comment]
运行不起来

**Comment by water4168** [comment]
@zmrenwu 加上随机字符串还是提示不能为空呀

**Comment by ghost** [comment]
见 #12
