### ISSUE TITLE
想问一下，对于人大经济论坛这种需要选择安全问题的网站怎么处理？

### ISSUE THREAD

**Issue by lxylky1688** [zmrenwu/pythonzh.cn#11]
需要安全问题选择的网站 需要怎么处理？
url = 'http://bbs.pinggu.org/'
params = {"username":"xingyun1688", "password": "xingyun888", "questionid":"你其中一位老师的名字", "answer":"于东海"}
这样做好像不行

**Comment by ghost** [comment]
Sorry，这么晚才回复。目前这个仓库不在维护中且不要用于生产环境。你的这个问题可以使用 https 传输。
