### ISSUE TITLE
添加了SECRET_KEY,但还是一直提示SECRET_KEY为空，怎么解决？

### ISSUE THREAD

**Issue by water4168** [zmrenwu/pythonzh.cn#12]
找了几天的答案，都试了没用！！！！！

**Comment by ghost** [comment]
Sorry，这个仓库目前不在维护中。可能的问题的是你在启动项目时，应该使用 settings.local 这个设置文件，且确保这个设置文件中 SECRET_KEY 不为空（没有就添加进去。）。如果只是为了体验论坛功能请访问：www.pythonzh.cn。
