### ISSUE TITLE
域名能不能更换一下

### ISSUE THREAD

**Issue by simcookies** [zmrenwu/pythonzh.cn#3]
域名目前是名字吧？release的时候可以更改域名吗？

**Comment by ghost** [comment]
会的，目前手头只有这个域名。当前只是为了开发时线上测试，并非正式运营。如仓库名 pythonzh.cn，将来上线时将使用该域名（已经注册，还在实名认证中，也许还要备案）。

**Comment by simcookies** [comment]
好的，我会一直关注这个项目的，希望能够建立一个权威的python社区。
