### ISSUE TITLE
很不错的项目，我一直在关注，最近我需要为SpaceVim社区做一个网站，在考虑用哪一个呢。

### ISSUE THREAD

**Issue by wsdjeg** [zmrenwu/pythonzh.cn#4]
我关注这个项目有一段时间了，我觉得在README里面应该有该项目已支持功能，或者和其他类似项目的对比，另外可以添加一些以此为模版实现的网站的链接。

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim 这是我的项目，有兴趣 可以来一起搞搞，如果你熟悉web方面的话。

**Comment by ghost** [comment]
谢谢支持！因为目前还处于内部开发阶段，测试不够完善，不接受 pr，暂时没有向外推广项目，所以没有完善相关文档。正在补充测试和重构代码，暂时不建议在生产环境使用。如果您想基于该项目搭建社区，请等待完善测试和文档的 alpha 版本发布。

**Comment by wsdjeg** [comment]
好的，谢谢，我会关注动态！
