### ISSUE TITLE
示例里的论坛样式有问题

### ISSUE THREAD

**Issue by EchoUtopia** [zmrenwu/pythonzh.cn#7]
你的论坛：http://yangxg.top/
在我的14存，1366*768分辨率屏幕的笔记本上显示是这样的：
![](http://wx3.sinaimg.cn/mw690/a17f346egy1fcw56rxl6cj20m004vaaa.jpg)
![](http://wx1.sinaimg.cn/mw690/a17f346egy1fcw57y1vbqj20li060wex.jpg)

**Comment by ghost** [comment]
谢谢！使用的是什么浏览器？

**Comment by EchoUtopia** [comment]
chrome 54还是55版本的,windows 10,我用台式机访问是没问题的
