### ISSUE TITLE
跑不起来。。。

### ISSUE THREAD

**Issue by lawtech0902** [zmrenwu/pythonzh.cn#8]
FieldError at /
Expression contains mixed types. You must set output_field

**Comment by xianfuxing** [comment]
可以的啊，你是哪个page有问题？

**Comment by lawtech0902** [comment]
@xianfuxing templates/forum/index.html，显示render template的时候出错

**Comment by xianfuxing** [comment]
完整的track信息，贴出来看看。

**Comment by xianfuxing** [comment]
还有project的根目录建立一个media目录

**Comment by lawtech0902** [comment]
@xianfuxing ![](http://ww2.sinaimg.cn/large/006tNbRwgy1ffu9tqg91jj31kw0tbk1q.jpg)

**Comment by lawtech0902** [comment]
@xianfuxing  麻烦了，我自己傻了，习惯性把数据库换成mysql，换回来就能运行了

**Comment by xianfuxing** [comment]
如此甚好

**Comment by ghost** [comment]
该项目暂停维护！很抱歉了。
